### ISSUE TITLE
Getting a given object

### ISSUE THREAD

**Issue by trokster** [redgeoff/delta-pouch#41]
Hi,

Sorry stupid question maybe. How do you pull a given object from the DB ? Say I have an object with $id = 123, is there a method akin to get, or would I need to manually merge it from all changes ?

**Comment by ruud12** [comment]
Hello,

Is there a specific reason for not implementing the get() functionality? I am also looking for this functionality. I would simply propose to change the "all()" function to:

- Allow an optional input parameter (doc ID)
- If the argument is present, add a startkey and endkey to the allDocs command
- Leave the rest of the function untouched. Users should check themselves if the function only returns 1 object

Code change in the export.all function would be something like: 
`return db.allDocs({include_docs: true, startkey: docID, endkey: docID+"_\ufff0"}).then(function (doc) {`

Would this be an option and if yes, shall I make a pull request with the proposed changes?
Thanks in advance!

**Comment by redgeoff** [comment]
Hey @ruud12! I think this is a good idea. Please name this new function `get`. I look forward to seeing the PR!
