### ISSUE TITLE
Merge

### ISSUE THREAD

**Issue by connelhooley** [redgeoff/delta-pouch#45]
I noticed a merge function in one of the demo's.

```
function onChange(doc) {
    profile = db.merge(profile, doc);
    display();
}
```

I cannot find this in in the [PouchDB API](http://pouchdb.com/api.html) if it is in this plug in, what does it do? Could something be added to the read me? thanks

**Comment by t-knapp** [comment]
The `merge(obj1, obj2)` function is implemented in the delta-pouch [plugin file](https://github.com/redgeoff/delta-pouch/blob/master/dist/pouchdb.delta-pouch.js#L1144).
