### ISSUE TITLE
'create' event is now removed

### ISSUE THREAD

**Issue by nolanlawson** [redgeoff/delta-pouch#47]
I didn't realize any plugins were actually depending on these events. They weren't documented, so we removed them (https://github.com/pouchdb/pouchdb/issues/3739).

So unfortunately you're going to have to create a `db.changes()` listener instead of listening to `db.on('change')`.

**Comment by redgeoff** [comment]
Closing as fixed by https://github.com/redgeoff/delta-pouch/pull/52
