### ISSUE TITLE
Does not work with Pouchdb v6.1.0

### ISSUE THREAD

**Issue by t-knapp** [redgeoff/delta-pouch#49]
I'm struggling with conflicts in my system based on CouchDB + PouchDB. I read about this plugin on the [official PouchDB site](https://pouchdb.com/guides/conflicts.html#accountants-dont-use-erasers). This sounds very interesting and may help solving the current conflict problem.

Unfortunately this plugin does not work with the latest version of PouchDB and CouchDB. 

So the question is if this plugin will be updated to work with the latest version?

Kind regads
Tobi

**Comment by redgeoff** [comment]
Closing as fixed by https://github.com/redgeoff/delta-pouch/pull/52
